{% set name = "dwave-ocean-sdk" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6e1cf5bd8d6f101655abc2e907c7f1912981a49457ff64ba12ba71b056647a30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-gate ==0.3.3
    - dwave-optimization ==0.4.2
    - dwave-samplers ==1.4.0
    - pyqubo ==1.4.0
    - dimod ==0.12.18
    - dwave-cloud-client ==0.13.2
    - dwave-greedy ==0.3.0
    - dwave-hybrid ==0.6.13
    - dwave-inspector ==0.5.2
    - dwave-neal ==0.6.0
    - dwave-networkx ==0.8.16
    - dwave-preprocessing ==0.6.7
    - dwave-system ==1.28.0
    - dwave-tabu ==0.5.0
    - dwavebinarycsp ==0.3.1
    - minorminer ==0.2.16
    - penaltymodel ==1.2.0
    - python >=3.7

test:
  imports:
    - dwaveoceansdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-ocean-sdk
  summary: Software development kit for open source D-Wave tools
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.ocean.dwavesys.com

extra:
  recipe-maintainers:
    - BastianZim
