{% set name = "dwave-ocean-sdk" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-ocean-sdk-{{ version }}.tar.gz
  sha256: cc497342d87660539ded4227b67f6fa825828d4814c5dcad02e8ef02e7cf295b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=46.4.0
    - wheel
  run:
    - dimod ==0.11.2
    - dwave-cloud-client ==0.10.1
    - dwave-greedy ==0.2.5
    - dwave-hybrid ==0.6.7
    - dwave-inspector ==0.2.11
    - dwave-neal ==0.5.9
    - dwave-networkx ==0.8.12
    - dwave-preprocessing ==0.4.0
    - dwave-system ==1.15.0
    - dwave-tabu ==0.4.5
    - dwavebinarycsp ==0.2.0
    - minorminer ==0.2.9
    - penaltymodel ==1.0.2
    - python >=3.7

test:
  imports:
    - dwaveoceansdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-ocean-sdk
  summary: Software development kit for open source D-Wave tools
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.ocean.dwavesys.com

extra:
  recipe-maintainers:
    - BastianZim
