{% set name = "dwave-ocean-sdk" %}
{% set version = "7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-ocean-sdk-{{ version }}.tar.gz
  sha256: d20f52bb7859ca039c4257273f6c26fd9f7d9354cfc7f0ab22f0cfa4752841b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=46.4.0
    - wheel
  run:
    - dimod==0.12.16
    - dwave-cloud-client==0.12.1
    - dwave-gate==0.3.2
    - dwave-greedy==0.3.0
    - dwave-hybrid==0.6.11
    - dwave-inspector==0.5.0.post0
    - dwave-neal==0.6.0
    - dwave-networkx==0.8.15
    - dwave-optimization==0.2.0
    - dwave-preprocessing==0.6.6
    - dwave-samplers==1.3.0
    - dwave-system==1.25.0
    - dwave-tabu==0.5.0
    - dwavebinarycsp==0.3.0
    - minorminer==0.2.15
    - penaltymodel==1.1.0
    - python >=3.7

test:
  imports:
    - dwaveoceansdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-ocean-sdk
  summary: Software development kit for open source D-Wave tools
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.ocean.dwavesys.com

extra:
  recipe-maintainers:
    - BastianZim
