{% set name = "dwave-ocean-sdk" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-ocean-sdk-{{ version }}.tar.gz
  sha256: c7496ad96e78b63db2a3551fbf4613eb414cdbe24f8bfe4b16494cc2c2a18960

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=46.4.0
    - wheel
  run:
    - dimod ==0.12.0
    - dwave-cloud-client ==0.10.3
    - dwave-greedy ==0.2.5
    - dwave-hybrid ==0.6.9
    - dwave-inspector ==0.3.0
    - dwave-neal ==0.5.9
    - dwave-networkx ==0.8.12
    - dwave-preprocessing ==0.5.0
    - dwave-system ==1.16.0
    - dwave-tabu ==0.4.5
    - dwavebinarycsp ==0.2.0
    - minorminer ==0.2.9
    - penaltymodel ==1.0.2
    - python >=3.7

test:
  imports:
    - dwaveoceansdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-ocean-sdk
  summary: Software development kit for open source D-Wave tools
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.ocean.dwavesys.com

extra:
  recipe-maintainers:
    - BastianZim
