{% set name = "dwave-ocean-sdk" %}
{% set version = "6.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-ocean-sdk-{{ version }}.tar.gz
  sha256: f9f3d185f15852cf408b1edd74e20785200ecba076fe950349ea84bb34e12731

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-samplers ==1.0.0
    - pyqubo ==1.4.0
    - dimod ==0.12.6
    - dwave-cloud-client ==0.10.5
    - dwave-greedy ==0.3.0
    - dwave-hybrid ==0.6.10
    - dwave-inspector ==0.4.2
    - dwave-neal ==0.6.0
    - dwave-networkx ==0.8.14
    - dwave-preprocessing ==0.5.4
    - dwave-system ==1.19.0
    - dwave-tabu ==0.5.0
    - dwavebinarycsp ==0.2.0
    - minorminer ==0.2.11
    - penaltymodel ==1.0.2
    - python >=3.7

test:
  imports:
    - dwaveoceansdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-ocean-sdk
  summary: Software development kit for open source D-Wave tools
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.ocean.dwavesys.com

extra:
  recipe-maintainers:
    - BastianZim
